### ISSUE TITLE
Do not show Sublime Protocol in dock when launched

### ISSUE THREAD

**Issue by svicalifornia** [saetia/sublime-url-protocol-mac#2]
Clicking on an "subl:" link causes Sublime Protocol to show in the dock and then quickly disappear, offsetting all of the other icons in the dock. I have seen many apps (such as menubar additions) that have an option to hide the dock icon when running. Please set the same option to Sublime Protocol so that the dock will not be affected when it runs.

**Comment by saetia** [comment]
Thanks for the suggestion! It shouldn't show up in the dock anymore

**Comment by svicalifornia** [comment]
Thanks! Works great.
