### ISSUE TITLE
Mavericks Installation

### ISSUE THREAD

**Issue by ghost** [saetia/sublime-url-protocol-mac#4]
In Mavericks when you try to run the Sublime Protocol.app in Applications and error message comes up:

```
"Sublime Protocol.app" can’t be opened because it is from an unidentified developer.
```

The workaround is to right-click (or ctrl-click) the Sublime Protocol.app and select "Open" then when prompted, click "Open" again.

I just thought this should be added to the README.md

Otherwise, thanks for the awesome project!

**Comment by saetia** [comment]
ah, thanks. i didn’t think about that. I’ll see if i’m able to codesign simple app bundles to prevent that warning

**Comment by saetia** [comment]
the app should be code signed now and not require this workaround. thanks again
